server:
  port: 8080

spring:
  application:
    name: betting-service

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: betting-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.betting.model.EventOutcome

  datasource:
    url: jdbc:h2:mem:betdb
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console