INSERT INTO BET (BET_ID, USER_ID, EVENT_ID, EVENT_MARKET_ID, EVENT_WINNER_ID, BET_AMOUNT, STATUS)
VALUES (1,'U1','E1','M1','TEAM_A',100,'PENDING');

INSERT INTO BET (BET_ID, USER_ID, EVENT_ID, EVENT_MARKET_ID, EVENT_WINNER_ID, BET_AMOUNT, STATUS)
VALUES (2,'U2','E1','M1','TEAM_B',200,'PENDING');

INSERT INTO BET (BET_ID, USER_ID, EVENT_ID, EVENT_MARKET_ID, EVENT_WINNER_ID, BET_AMOUNT, STATUS)
VALUES (3,'U3','E1','M1','TEAM_B',200,'PENDING');

INSERT INTO BET (BET_ID, USER_ID, EVENT_ID, EVENT_MARKET_ID, EVENT_WINNER_ID, BET_AMOUNT, STATUS)
VALUES (4,'U4','E1','M1','TEAM_A',50,'PENDING');